# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f35283c19eef972658ede6572856d169d21c7da94e8f8c38fb870abcd8317dcc99ad16e141635862f75a24c9439cc321e6ca1657470766aede2c10f086e3bbf1

test:
  secret_key_base: c0a4d90b6782420b420b86b0bd4b65a7c559023fc3922082f13289e898863ea5ed33d720cffe37a4f27c117ae181fa6b33fd3def50e0af364680db010085c686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
